### ISSUE TITLE
Runtime error

### ISSUE THREAD

**Issue by lekting** [pkujhd/goloader#17]
Hello, i have grab default loader code and when i'm trying to run my program - i got error, when i'm removing creating new variable with my struct (*base.TCPServer) code running normaly. Have i do something wrong?

My code
```go
type teset struct {
	Name *base.TCPServer
}

func main() {

	runtime.GOMAXPROCS(runtime.NumCPU())

	symPtr := make(map[string]uintptr)
	err := goloader.RegSymbol(symPtr)
	if err != nil {
		fmt.Println(err)
		return
	}
	goloader.RegTypes(symPtr, time.Duration(0), time.Unix(0, 0))
	goloader.RegTypes(symPtr, runtime.LockOSThread)

	reloc, err := goloader.ReadObjs([]string{"../plugins/test.o"}, []string{""})
	if err != nil {
		fmt.Println(err)
		return
	}
	symPtr["os.Stdout"] = uintptr(unsafe.Pointer(&os.Stdout))

	codeModule, err := goloader.Load(reloc, symPtr)
	if err != nil {
		fmt.Println("Load error:", err)
		return
	}
	runFuncPtr := codeModule.Syms["main.mainb"]
	if runFuncPtr == 0 {
		fmt.Println("Load error! not find function:", "main.mainb")
		return
	}
	funcPtrContainer := (uintptr)(unsafe.Pointer(&runFuncPtr))
	runFunc := *(*func())(unsafe.Pointer(&funcPtrContainer))
	runFunc()
	os.Stdout.Sync()
	codeModule.Unload()

	_ = &teset{
		Name: &base.TCPServer{Port: "11", Protocol: "tcp"},
	}
}
```

Error
```
runtime: nameOff 0x245c8b48 base 0x5704f0 not in ranges:
        types 0x81b000 etypes 0x9e9420
fatal error: runtime: name offset base pointer out of range

goroutine 1 [running]:
runtime.throw(0x93024d, 0x2e)
        D:/programms/golangg/src/runtime/panic.go:1116 +0x79 fp=0xc00047d970 sp=0xc00047d940 pc=0x438069
runtime.resolveNameOff(0x5704f0, 0x245c8b48, 0x23)
        D:/programms/golangg/src/runtime/type.go:210 +0x245 fp=0xc00047d9d8 sp=0xc00047d970 pc=0x460915
reflect.resolveNameOff(0x5704f0, 0xc0245c8b48, 0x413e32)
        D:/programms/golangg/src/runtime/runtime1.go:482 +0x3a fp=0xc00047da00 sp=0xc00047d9d8 pc=0x44947a
reflect.(*rtype).nameOff(...)
        D:/programms/golangg/src/reflect/type.go:683
reflect.(*rtype).String(0x5704f0, 0x0, 0xf362259b0160f322)
        D:/programms/golangg/src/reflect/type.go:753 +0x3d fp=0xc00047da38 sp=0xc00047da00 pc=0x48f02d
reflect.(*rtype).Elem(0x5704f0, 0x9d4000, 0x5704f0)
        D:/programms/golangg/src/reflect/type.go:912 +0x137 fp=0xc00047da80 sp=0xc00047da38 pc=0x490227
github.com/pkujhd/goloader.regItab(0xc00047de28, 0xc0001aa150, 0x6d, 0x9ca0e0)
        C:/Users/gorni/go/src/github.com/pkujhd/goloader/register.go:107 +0x2b0 fp=0xc00047db40 sp=0xc00047da80 pc=0x8191a0
github.com/pkujhd/goloader.RegSymbol(0xc00047de28, 0x0, 0x0)
        C:/Users/gorni/go/src/github.com/pkujhd/goloader/register.go:91 +0x2d0 fp=0xc00047dcf8 sp=0xc00047db40 pc=0x818cb0
main.main()
        C:/Users/gorni/go/src/brewellcore/server/main.go:24 +0xb3 fp=0xc00047df88 sp=0xc00047dcf8 pc=0x81aab3
runtime.main()
        D:/programms/golangg/src/runtime/proc.go:203 +0x1fa fp=0xc00047dfe0 sp=0xc00047df88 pc=0x43a71a
runtime.goexit()
        D:/programms/golangg/src/runtime/asm_amd64.s:1373 +0x1 fp=0xc00047dfe8 sp=0xc00047dfe0 pc=0x468f11
```

**Comment by lekting** [comment]
this changes in code of file register.go makes my program able to start and work normal

```go
func regItab(symPtr map[string]uintptr, name string, addr uintptr) {
	symPtr[name] = addr
	bss := strings.Split(strings.TrimLeft(name, ITAB_PREFIX), ",")
	slice := sliceHeader{addr, len(bss), len(bss)}
	ptrs := *(*[]unsafe.Pointer)(unsafe.Pointer(&slice))
	for i, ptr := range ptrs {
		tname := bss[len(bss)-i-1]
		if tname[0] == '*' {
			obj := reflect.TypeOf(0)
			(*emptyInterface)(unsafe.Pointer(&obj)).word = ptr

			prefix := TYPE_PREFIX + tname[1:]

                        //obj = obj.(reflect.Type).Elem()
		        //symPtr[prefix] = uintptr((*emptyInterface)(unsafe.Pointer(&obj)).word)

			if symPtr[prefix] != 0 {
				obj = obj.(reflect.Type).Elem()
				symPtr[prefix] = uintptr((*emptyInterface)(unsafe.Pointer(&obj)).word)
			}
		}
		symPtr[TYPE_PREFIX+tname] = uintptr(ptr)
	}
}
```

**Comment by pkujhd** [comment]
@lekting 
could you give me test.o go file, and base package, i can't reappear this case with now information.
in addition, with your golang version

**Comment by lekting** [comment]
@pkujhd 
Yeah sure, go version:
```go version go1.14.4 windows/amd64```

Update: i have found place with error. My struct TCPServer have a pointer to the another struct World where there is a function that uses library go-mc:
https://github.com/Tnze/go-mc/blob/master/nbt/nbt.go#L36

function new() gives an error, also this happens when i'm using hashing (adler32)
https://github.com/golang/go/blob/master/src/hash/adler32/adler32.go#L44

test.go
```go
func mainb(server *base.TestTCPServer) {
	fmt.Println("here")
	fmt.Println(server.Protocol)
}

func main() {
       //Empty because needed in main package
}
```

main.go
```go
func main() {

	runtime.GOMAXPROCS(runtime.NumCPU())

	//packets.InitPackets()
	server := &base.TestTCPServer{Port: "25565", Protocol: "tcp"}
	symPtr := make(map[string]uintptr)
	err := goloader.RegSymbol(symPtr)
	if err != nil {
		fmt.Println(err)
		return
	}

	goloader.RegTypes(symPtr, time.Duration(0), time.Unix(0, 0))
	goloader.RegTypes(symPtr, runtime.LockOSThread)
	//goloader.RegTypes(symPtr, server)

	reloc, err := goloader.ReadObjs([]string{"../plugins/test.o"}, []string{""})
	if err != nil {
		fmt.Println(err)
		return
	}
	symPtr["os.Stdout"] = uintptr(unsafe.Pointer(&os.Stdout))

	codeModule, err := goloader.Load(reloc, symPtr)
	if err != nil {
		fmt.Println("Load error:", err)
		return
	}
	runFuncPtr := codeModule.Syms["main.mainb"]
	if runFuncPtr == 0 {
		fmt.Println("Load error! not find function:", "main.mainb")
		return
	}
	funcPtrContainer := (uintptr)(unsafe.Pointer(&runFuncPtr))
	runFunc := *(*func(server *base.TestTCPServer))(unsafe.Pointer(&funcPtrContainer))
	runFunc(server)
	os.Stdout.Sync()
	codeModule.Unload()
}
```

TCPServer
```go
package base

import (
	"brewellcore/server/world"
	"fmt"
	"net"
)

// TCPServer struct
type TestTCPServer struct {
	Protocol string
	Port     string
	Net      net.Listener
	World    *world.Map
}

//var players []*UserConnection

func (server *TestTCPServer) Run() {
	server.Net, _ = net.Listen(server.Protocol, ":"+server.Port)

	world.Generate(server.World)

	fmt.Println("[Server|Generator] World loaded")

	for {
		_, _ = server.Net.Accept()

		//go server.handleRequest(conn)
	}
}
```

World
```go
func Generate(world *Map) {

	files, err := ioutil.ReadDir("testworld/region/")
	if err != nil {
		log.Fatal(err)
	}

	for _, file := range files {
		r, err := region.Open("testworld/region/" + file.Name())

		if err != nil {
			fmt.Println(err)
			return
		}
		defer r.Close()

		for x := 0; x < 32; x++ {
			for z := 0; z < 32; z++ {
				data, err := r.ReadSector(region.In(x, z))
				if err != nil {
					continue
				}

				r, err := zlib.NewReader(bytes.NewReader(data[1:]))
				if err != nil {
					continue
				}

				nbt.NewDecoder(r)  <<HERE ERROR
			}
		}
	}
}
```

**Comment by pkujhd** [comment]
@lekting , means now you modify your code, previous error already disappeared? 
i still do not reappear error with newer code in go 1.14.4 on windows/amd64.

**Comment by lekting** [comment]
@pkujhd , yeah, i'll modify my code to make its working, this error happens sometimes and i don't know why, I will study more problems and let you know if I find out something. Thanks for library 👍
