### ISSUE TITLE
syscall panic: function header modified, can not relocate TLS

### ISSUE THREAD

**Issue by Atsika** [pkujhd/goloader#48]
Hi,
I'm trying to load an object file with the following content : 
```Go
package main

import (
	"fmt"
	"syscall"
)

func main() {
	fmt.Println("PID:", syscall.Getpid())
}
```
I'm compiling it with : 
```
go tool compile pid.go
```

When trying to run it with the example loader, I got  the following error : 
```
panic: function header modified, can not relocate TLS

goroutine 1 [running]:
github.com/pkujhd/goloader.regTLS(0x693b40, {0x41aa0000, 0x3e, 0x5})
        /home/atsika/go/pkg/mod/github.com/pkujhd/goloader@v0.0.0-20220117070920-c3c121e5f3c6/register.go:99 +0x154
github.com/pkujhd/goloader.(*Linker).relocate(0xc000168300, 0xc00012c420, 0xc00012c420)
        /home/atsika/go/pkg/mod/github.com/pkujhd/goloader@v0.0.0-20220117070920-c3c121e5f3c6/dymcode.go:552 +0x7ad
github.com/pkujhd/goloader.Load(0xc000168300, 0x1)
        /home/atsika/go/pkg/mod/github.com/pkujhd/goloader@v0.0.0-20220117070920-c3c121e5f3c6/dymcode.go:728 +0x354
main.main()
        /run/media/atsika/SSD/tools/my-project/goloader/examples/loader/loader.go:88 +0x745
```
Any idea why is this happening ?

Thanks in advance

**Comment by pkujhd** [comment]
@Atsika  please give me your environment, golang version/os version.

**Comment by Atsika** [comment]
```
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/atsika/.cache/go-build"
GOENV="/home/atsika/.config/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/home/atsika/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/atsika/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/home/atsika/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/home/atsika/go/pkg/tool/linux_amd64"
GOVCS=""
GOVERSION="go1.17.2"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/run/media/atsika/SSD/tools/my-project/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build2814997685=/tmp/go-build -gno-record-gcc-switches"
```

**Comment by pkujhd** [comment]
@Atsika golang 1.17 change TLS, need adapter it

**Comment by Atsika** [comment]
I see. Is there a way you push the modified code ? or at least explain me how to do it ?
Thanks for your time

**Comment by pkujhd** [comment]
@Atsika 
it is diffcult to give a perfect modification. i need time.
if you block now,  use it replace panic code.
```
				symPtr[TLSNAME] = 0xfffffff8
				return
```
it works on linux/amd64
it is a temporary modification

**Comment by Atsika** [comment]
I'll give a try to this hotfix, thanks.


Do you have any documentation I can read so I can understand TLS in Go ?

**Comment by pkujhd** [comment]
I am sorry, no document
I basically learned it by reading golang source code

**Comment by Atsika** [comment]
I see. Great job !

Does this error happen also in versions >1.17 ? If not, I can maybe just update my Go version as a workaround.

**Comment by pkujhd** [comment]
It is not exist in golang version < 1.17.
I will be rewrite get TLS offset code, but it need some time
