### ISSUE TITLE
window run loader.exe -o base.o -times 2 coredump

### ISSUE THREAD

**Issue by pkujhd** [pkujhd/goloader#7]
D:\Code\go\goloader>loader.exe -o base.o -times 2
{1 2}
{1 2} &{1 2} {1 0} {0 0}
main.Vertex{X:1, Y:2} &main.Vertex{X:1, Y:2} main.Vertex{X:1, Y:0} main.Vertex{X:0, Y:0}
print &{1 2}
[John Paul George Ringo]
[{2 true} {3 false}]
map[Bell Labs:{40 -74} Google:{37 -122}]
Don't know type string
panic: this is a panic test
Stack of 465 bytes:
goroutine 1 [running]:
main.logPanic()
        D:/Code/go/src/github.com/pkujhd/goloader/examples/base/base.go:115 +0xc8
panic(0x6c5aa0, 0x2852043)
        D:/ProgramFiles/go/src/runtime/panic.go:502 +0x237
main.recoverTest()
        D:/Code/go/src/github.com/pkujhd/goloader/examples/base/base.go:109 +0x5c
main.main()
        D:/Code/go/src/github.com/pkujhd/goloader/examples/base/base.go:85 +0x6d3
main.main()
        D:/Code/go/src/github.com/pkujhd/goloader/examples/loader/loader.go:95 +0x8fd

0 0
1 -2
3 -6
6 -12
10 -20
15 -30
21 -42
28 -56
36 -72
45 -90
I'm an int
I'm a bool
Exception 0xc0000005 0x1 0xb 0x2850ba0
{1 2}
PC=0x2850ba0

runtime: unknown pc 0x2850ba0
stack: frame={sp:0xc0427fdf50, fp:0x0} stack=[0xc0427fc000,0xc0427fe000)
{1 2} &{1 2} {1 0} {0 0}
000000c0427fde50:  000000c042472890  000000c0424728a8
000000c0427fde60:  000000c0427fde88  00000000004b9e55 main.Vertex{X:1, Y:2} &main.Vertex{X:1, Y:2} main.Vertex{X:1, Y:0} main.Vertex{X:0, Y:0}
<print &{1 2}
fmt.(*pp).free+149>
000000c0427fde70:  00000000008fdf90  00000000007351a0
000000c0427fde80:  000000c0427fe000  000000c0427fdef0
000000c0427fde90:  [John Paul George Ringo]
00000000004ba82e <fmt.Fprintln+190>  000000c0427fe000
000000c0427fdea0:  000000c042008030  000000000000000b
000000c0427fdeb0:  0000000000000010  000000000000000b
000000c0427fdec0:  0000000000000000  0000000000000000
000000c0427fded0:  000000000000000b  000000c0427fe000
000000c0427fdee0:  0000000000000000  0000000000000000
000000c0427fdef0:  000000c0427fdf40  00000000004ba8ce <fmt.Println+[{2 true} {3 false}]
94>
000000c0427fdf00:  000000000078d6e0  000000c042086008
map[Google:{37 -122} Bell Labs:{40 -74}]
000000c0427fdf10:  000000c0427fdfb0  0000000000000001
Don't know type string
000000c0427fdf20:  0000000000000001  000000000000000b
000000c0427fdf30:  0000000000000000  0000000000000000
000000c0427fdf40:  000000c0427fdfc0  0000000002850ba0
000000c0427fdf50: <000000c0427fdfb0  0000000000000001
000000c0427fdf60:  0000000000000001  000000000000000b
000000c0427fdf70:  0000000000000000  0000000000000000
000000c0427fdf80:  0000000000000000  0000000000000000
000000c0427fdf90:  0000000000000000  0000000000000000
000000c0427fdfa0:  0000000000000000  0000000000000000
000000c0427fdfb0:  00000000006c5aa0  0000000002851fb9
000000c0427fdfc0:  0000000000000000  I'm a bool
0000000000454611 <runtime.goexit+1>
000000c0427fdfd0I'm an int
:  00000000006c3520  00000000008cd8e1
000000c0427fdfe0:  0000000000000000  0000000000000000
000000c0427fdff0:  0000000000000000  0000000000000000
runtime: unknown pc 0x2850ba0
stack: frame={sp:0xc0427fdf50, fp:0x0} stack=[0xc0427fc000,0xc0427fe000)
000000c0427fde50:  000000c042472890  000000c0424728a8
000000c0427fde60:  000000c0427fde88  00000000004b9e55 <fmt.(*pp).free+149>
000000c0427fde70:  00000000008fdf90  00000000007351a0
000000c0427fde80:  000000c0427fe000  000000c0427fdef0
000000c0427fde90:  00000000004ba82e <fmt.Fprintln+190>  000000c0427fe000
000000c0427fdea0:  000000c042008030  000000000000000b
000000c0427fdeb0:  0000000000000010  000000000000000b
000000c0427fdec0:  0000000000000000  0000000000000000
000000c0427fded0:  000000000000000b  000000c0427fe000
000000c0427fdee0:  0000000000000000  0000000000000000
000000c0427fdef0:  000000c0427fdf40  00000000004ba8ce <fmt.Println+94>
000000c0427fdf00:  000000000078d6e0  000000c042086008
000000c0427fdf10:  000000c0427fdfb0  0000000000000001
000000c0427fdf20:  0000000000000001  000000000000000b
000000c0427fdf30:  0000000000000000  0000000000000000
000000c0427fdf40:  000000c0427fdfc0  0000000002850ba0
000000c0427fdf50: <000000c0427fdfb0  0000000000000001
000000c0427fdf60:  0000000000000001  000000000000000b
000000c0427fdf70:  0000000000000000  0000000000000000
000000c0427fdf80:  0000000000000000  0000000000000000
000000c0427fdf90:  0000000000000000  0000000000000000
000000c0427fdfa0:  0000000000000000  0000000000000000
000000c0427fdfb0:  00000000006c5aa0  0000000002851fb9
000000c0427fdfc0:  0000000000000000  0000000000454611 <runtime.goexit+1>
000000c0427fdfd0:  00000000006c3520  00000000008cd8e1
000000c0427fdfe0:  0000000000000000  0000000000000000
000000c0427fdff0:  0000000000000000  0000000000000000

goroutine 1 [running]:
        goroutine running on other thread; stack unavailable
rax     0xb
rbx     0x0
rcx     0x0
rdi     0xc042054258
rsi     0x0
rbp     0xc0427fdfc0
rsp     0xc0427fdf50
r8      0xc041ffd5ee
r9      0x1
r10     0xc042054250
r11     0x1
r12     0x40
r13     0x40
r14     0x77
r15     0x18
rip     0x2850ba0
rflags  0x10206
cs      0x33
fs      0x53
gs      0x2b

**Comment by pkujhd** [comment]
go 1.10

**Comment by pkujhd** [comment]
loader.go exec main.main function and unload module Immediately, but print is async, it maybe access string data on unload memory.  so modify load.go

**Comment by pkujhd** [comment]
https://github.com/pkujhd/goloader/commit/e0fbf61c975fab064a0b76eb2506dd92f3696154 sync os.Stdout before unload module
